/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospitalautomation.UI;

import com.hospitalautomation.Business.IDoctorService;
import com.hospitalautomation.Business.IPatientService;
import com.hospitalautomation.Business.IPersonalService;
import com.hospitalautomation.Business.IocConfig;
import com.hospitalautomation.Entities.Doctor;
import com.hospitalautomation.Entities.Patient;
import com.hospitalautomation.Entities.Personal;
import javax.swing.JFrame;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 *
 * @author Monster
 */
public class AccessMain extends javax.swing.JFrame {

    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(IocConfig.class);
        
    final IDoctorService doctorService = context.getBean("doctorService",IDoctorService.class);
    final IPatientService patientService = context.getBean("patientService",IPatientService.class);
    final IPersonalService personalService = context.getBean("personalService",IPersonalService.class);
    public AccessMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPatientLogin = new javax.swing.JButton();
        btnDoctorLogin1 = new javax.swing.JButton();
        btnPersonalLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 643));

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hospitalautomation/UI/Images/AccessPage.jpg"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 432));
        jPanel2.setPreferredSize(new java.awt.Dimension(506, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DUZCE UNIVERSITY HOSPITAL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 560, 80));

        btnPatientLogin.setText("Patient Login");
        btnPatientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnPatientLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 198, 42));

        btnDoctorLogin1.setText("Doctor Login");
        btnDoctorLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDoctorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 198, 42));

        btnPersonalLogin.setText("Personal Login");
        btnPersonalLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnPersonalLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 198, 42));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalLoginActionPerformed
       Personal personal = personalService.getByUserName(Thread.currentThread().getName());
        if (personal != null) {
           PersonalProcessings personalProcessings = new PersonalProcessings();
           personalProcessings.setVisible(true);
        }
        PersonalLoginPage personalLoginPage = new PersonalLoginPage();
        personalLoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPersonalLoginActionPerformed

    private void btnDoctorLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorLogin1ActionPerformed
        Doctor doctor = doctorService.getByUserName(Thread.currentThread().getName());
        if (doctor != null) {
           DoctorProcessings doctorProcessings = new DoctorProcessings();
           doctorProcessings.setVisible(true);
        }
        DoctorLoginPage doctorLoginPage = new DoctorLoginPage();
        doctorLoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDoctorLogin1ActionPerformed

    private void btnPatientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLoginActionPerformed
        Patient patient = patientService.getByUserName(Thread.currentThread().getName());
        if (patient != null) {
           PatientProcessings patientProcessings = new PatientProcessings();
           patientProcessings.setVisible(true);
        }
        PatientLoginPage patientLoginPage = new PatientLoginPage();
        patientLoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPatientLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctorLogin1;
    private javax.swing.JButton btnPatientLogin;
    private javax.swing.JButton btnPersonalLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
